version: '3.8'

volumes:
  postgres_data:
  redis_data:

services:
  postgres:
    image: postgres:16.3-alpine
    container_name: flight-booking-system-postgres
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
  redis:
    image: redis:7.2.4-alpine
    container_name: flight-booking-system-redis
    command: --port ${REDIS_PORT}
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    volumes:
      - type: volume
        source: redis_data
        target: /data
